accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('edit/', views.edit, name='edit'),
    path('logout/', views.user_logout, name='logout'),
]

blogposts/urls.py
from django.urls import path
from . import views

app_name = 'blogposts'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('', views.list_post, name='list'),
    path('list/<str:author>/<int:author_id>/<slug:slug>/',
         views.detail_post, name='detail'),
    path('<str:author>/<int:author_id>/',
         views.user_post_list, name='user_post_list'),
    path('update/<str:author>/<int:author_id>/<slug:slug>/',
         views.update_post, name='update'),
    path('delete/<int:author_id>/<slug:slug>/',
         views.delete_post, name='delete'),
]

problog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('blogposts.urls', namespace='blogposts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<footer class="bg-dark btn-block border-top border-warning overflow-hidden">
  <p class="py-2 h2 text-light text-center">&copy; BLOGPOST 2020</p>
</footer>

templates/partials/jumbotron.html
<div
  class="jumbotron jumbotron-fluid text-danger border-bottom border-warning"
  style="
    background: url('https://images.pexels.com/photos/3740740/pexels-photo-3740740.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')
      no-repeat center center/cover;
    background-attachment: fixed;

    height: 60vh;
    display: flex;
    justify-content: center;
    z-index: 0;
  "
  height="90vh"
>
  <div
    class="container d-flex flex-column justify-content-center align-items-center"
  >
    <p
      style="text-shadow: 5px 5px 5px #444;"
      class="h1 text-warning font-weight-bold"
    >
      Read Your Favourite <span class="text-light"> Blog Posts</span>
    </p>
    <p
      style="text-shadow: 5px 5px 5px #555;"
      class="lead text-warning font-weight-bold"
    >
      In today's world internet is the most popular way of reading blogs ...
    </p>

    <div class="text-center">
      <form class="form-inline my-2 my-lg-0">
        <div class="form-group">
          <input
            class="form-control mr-sm-2 mb-3 py-4 px-5"
            name="q"
            type="search"
            placeholder="Search"
          />
        </div>
      </form>
    </div>

    {% if status %}
        {% if request.user.is_authenticated %}
    <div class="text-center">
      <a href="?q=published" class="btn btn-warning text-dark font-weight-bold"
        >Published Posts</a
      >
      <a href="?q=draft" class="btn btn-dark text-warning font-weight-bold"
        >UnPublished Posts</a
      >
    </div>
    {% endif %}
    {% endif %}
  </div>
</div>

templates/partials/navbar.html
<nav
  class="navbar navbar-expand-lg navbar-dark bg-dark px-5 border-bottom border-warning"
>
  <div class="container">
    <a class="h1 navbar-brand" href="{% url 'blogposts:list' %}"
      ><span class="text-warning font-weight-bold h2">BLOG</span>
      <span class="font-weight-bold h2">POSTS</span></a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogposts:list' %}">Home </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'blogposts:user_post_list' author=request.user.username author_id=request.user.id %}"
            >Your Posts
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogposts:create' %}"
            >Create Posts
          </a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
          >
            <img
              width="40px"
              height="40px"
              class="rounded-circle"
              src="{% if  request.user.profile.photo %}/media/{{request.user.profile.photo}} {% else %} /static/img/anonymous.png {% endif %}"
              alt=""
            />
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:edit' %}"
              >Edit Profile</a
            >
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}"
              >Logout</a
            >
          </div>
        </li>
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/rough.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-11 mx-auto">
      <div class="row">
        <div class="col-md-6">
          {% for obj in objects %}
          <div class="card shadow m-3 w-75">
            <img src="" alt="" class="card-img-top img-fluid" />
            <div class="card-body">
              <h1 class="card-title">{{ obj.title|upper }}</h1>
              <p class="card-text text-dark h6">
                {{obj.body|safe|truncatewords:20}}
              </p>
              <a
                class="btn btn-light btn-large"
                href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
                >Read More</a
              >
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="offset-md-1 col-md-3">
          <div class="card">
            <div class="card-header">
              Authors
            </div>
            <ul class="list-group list-group-flush">
              {% for user in users %}

              <li class="list-group-item">
                <a
                  href="{% url 'blogposts:user_post_list' author=user.username author_id=user.id  %}"
                  >{{ user.username }}
                </a>
              </li>

              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% extends 'base.html' %} {% block content %} {% for obj in
objects %}
<br />{{forloop.counter}}|<a
  href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
  >{{obj.title}}</a
>|{{obj.body|safe}}|<br />
<a
  href="{% url 'blogposts:update' author=obj.author author_id=obj.author.id slug=obj.slug %}"
  >Update</a
>
{% empty %}
<h1>no posts has been made</h1>
{% endfor %} {% endblock %}

templates/partials/showcase.html
{% load static %}
<div class="card bg-dark text-white">
  <img
    height="300px"
    src="{% static 'img/showcase-3.jpg' %}"
    class="card-img border-none"
    alt="showcase"
  />
  <div
    class="card-img-overlay d-flex flex-column justify-content-center align-items-center"
  >
    <h1 class="card-title display-1">BLOG ZONE</h1>
    <p class="card-text lead">
      This is a wider card with supporting text below as a natural lead-in to
      additional content. This content is a little bit longer.
    </p>
    <form method="get">
      <div width="400px" class="input-group">
        <input
          class="form-control rounded mr-3"
          placeholder="Search post"
          type="text"
          name="q"
        />
        <button type="submit" class="btn btn-light">
          Search
        </button>
      </div>
    </form>
  </div>
</div>