blogposts/urls.py
from django.urls import path
from . import views

app_name = 'blogposts'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('', views.list_post, name='list'),
    path('list/<str:author>/<int:author_id>/<slug:slug>/',
         views.detail_post, name='detail'),
    path('<str:author>/<int:author_id>/',
         views.user_post_list, name='user_post_list'),
    path('update/<str:author>/<int:author_id>/<slug:slug>/',
         views.update_post, name='update'),
    path('delete/<int:author_id>/<slug:slug>/',
         views.delete_post, name='delete'),
]

problog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('blogposts.urls', namespace='blogposts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogposts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
import uuid
from ckeditor.fields import RichTextField
from django.utils.text import slugify

# Create your models here.


def image_path(_, filename):
    extension = filename.split('.')[-1]
    unique_id = uuid.uuid4().hex
    new_file_name = unique_id+'.'+extension
    new_file_name = f"{str(_.publish)}/{str(_.author)}/{new_file_name}"
    return "post/"+new_file_name


class PublishedPost(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    image = models.ImageField(
        upload_to=image_path, null=True, blank=True)
    slug = models.SlugField(max_length=250,
                            editable=True, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='blog_posts', default=1)
    body = RichTextField()
    publish = models.DateField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()  # The default manager.
    published = PublishedPost()  # Our custom manager.
    tags = TaggableManager()  # For managing tag
    count = models.IntegerField(default=0)

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    @staticmethod
    def draft():
        return Post.objects.all().filter(status='draft')

blogposts/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post


class PostForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title',  'image', 'body', 'status', 'tags']
        required = {
            'author': False
        }

    def __init__(self,  *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True, *args, **kwargs):
        obj = super(PostForm, self).save(commit=False, *args, **kwargs)

        from django.utils.text import slugify
        obj.slug = slugify(obj.title)
        if commit:
            obj.save()
        return obj


class PostCreateForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title', 'author', 'image', 'body', 'status', 'tags']

    def __init__(self,  *args, **kwargs):
        super(PostCreateForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({'class': 'form-control'})
        self.fields['author'].widget.attrs.update({'style': 'display:none;'})
        self.fields['author'].label = ''

blogposts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from .models import Post
from .forms import PostForm, PostCreateForm
from django.core.paginator import Paginator
from django.db.models import Q


def list_post(request):
    objects = Post.published.all().order_by('-created')
    feartured = Post.published.all().order_by('count')[:6]
    print(request.GET.get('q'))
    if request.GET.get('q'):
        value = request.GET.get('q')
        objects = Post.objects.filter(
            Q(title__icontains=value) | Q(body__icontains=value) | Q(author__username=value))
        objects = objects.order_by('-created')
    users = User.objects.all()
    paginator = Paginator(objects, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blogposts/common_list.html',
                  {'objects': page_obj, 'users': users, 'featured': feartured, 'page_obj': page_obj})


def user_post_list(request, author, author_id):
    objects = Post.objects.all().filter(Q(author__username=author)
                                        | Q(author__id=author_id))
    objects = objects.order_by('-created')
    if not request.user.is_authenticated:
        objects = Post.objects.all().filter(status='published').filter(author__username=author).filter(
            author__id=author_id)
        objects = objects.order_by('-created')

    print(objects)
    if request.GET.get('q'):
        value = request.GET.get('q')
        print(value)
        objects = objects.filter(
            Q(title__icontains=value) | Q(body__icontains=value) | Q(author__username=value) | Q(
                status__icontains=value))

    user = get_object_or_404(User, pk=author_id)
    paginator = Paginator(objects, 4)
    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    return render(request, 'blogposts/user_list.html',
                  {'objects': page_obj, 'page_obj': page_obj, 'user': user, 'counts': objects.count})


def detail_post(request, author, author_id, slug):
    objects = get_object_or_404(
        Post, author__username=author, author__id=author_id, slug=slug)

    objects.count = objects.count + 1
    objects.save()

    return render(request, 'blogposts/detail.html', {'objects': objects})


def create_post(request):
    form = PostCreateForm()
    if request.method == 'POST':
        form = PostCreateForm(
            data=request.POST, files=request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save(commit=False)
            obj.author = request.user
            obj.save()

            return redirect('blogposts:user_post_list', request.user.username, request.user.id)
    return render(request, 'blogposts/create.html', {'form': form})


def update_post(request, author, author_id, slug):
    obj = get_object_or_404(Post, author__id=author_id,
                            author__username=author, slug=slug)

    form = PostForm(instance=obj)
    if request.method == 'POST':
        form = PostForm(instance=obj, data=request.POST, files=request.FILES)

        print('error p1')
        if form.is_valid():
            print('error2')
            form.save()
            print('erro3')
            return redirect('blogposts:user_post_list', request.user.username, request.user.id)

    return render(request, 'blogposts/update.html', {'form': form})


def delete_post(request, author_id, slug):
    obj = get_object_or_404(Post, author__id=author_id, slug=slug)
    obj.delete()
    return redirect('blogposts:user_post_list', request.user.username, request.user.id)

templates/blogposts/common_list.html
{% extends 'base.html' %} {% block content %}
{% include 'partials/jumbotron.html' %}
<div class="row my-2">
  <div class="offset-1 col-3 offset-md-1 col-md-3 mt-3">
    <div class="card bg-warning text-dark mb-5 ">
      <div class="card-header font-weight-bold">
        Featured Posts
      </div>
      <ul class="list-group list-group-flush">
        {% for obj in featured %}

        <li class="list-group-item">
          <a
            href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
            >{{ obj.title|upper }}
          </a>
        </li>

        {% endfor %}
      </ul>
    </div>
 
    <div class="card bg-secondary text-warning ">
      <div class="card-header font-weight-bold">
        Authors
      </div>
      <ul class="list-group list-group-flush">
        {% for user in users %}

        <li class="list-group-item">
          <a
            href="{% url 'blogposts:user_post_list' author=user.username author_id=user.id  %}"
            >{{ user.username|upper }}
          </a>
        </li>

        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="col-8 col-md-8">
    {% for obj in objects %}
    <div class="card shadow border-secondary d-inline-block mx-3 mb-3" style="width: 20rem;">
      <div class="card-header text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-pencil-square"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
          />
          <path
            fill-rule="evenodd"
            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
          />
        </svg>
        {{obj.author}}
        <li class="float-right list-unstyled">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-clock"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm8-7A8 8 0 1 1 0 8a8 8 0 0 1 16 0z"
          />
          <path
            fill-rule="evenodd"
            d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"
          />
        </svg>
        {{obj.created|date}}</li>
      </div>
      <img
        width="300px"
        height="200px"
        src="/media/{{ obj.image }}"
        class="card-img-top"
        alt="..."
      />
      <div style="height: 8rem;" class="card-body">
        <h6 class="card-title text-justify h6">{{ obj.title|truncatewords:5 }}</h6>
        
        <a
          href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
          class="btn btn-secondary"
          >Read More...</a
        >
      </div>
      <div class="card-footer text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-eye-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
          <path
            fill-rule="evenodd"
            d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
          />
        </svg>
       <h5 class="badge badge-secondary">{{obj.count}}</h5> 
        <li class="float-right list-unstyled">
        <svg
          class="text-right"
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-tags-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 7.586 1H3zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"
          />
          <path
            d="M1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"
          />
        </svg>
        {% for tag in obj.tags.names %}
     {{tag }}
        {% endfor %}
      </div></li>
    </div>
    {% empty %}
    <div class="d-flex pt-5 justify-content-center align-items-center">
      <p class="bg-warning mt-5 p-5 shadow h1 text-danger">User have no post</p>
    </div>
    {% endfor %}
    <div class="pagination row text-center">
      <div class="col-6 mx-auto" >
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a class="btn btn-sm btn-warning" href="?page=1">&laquo; first</a>
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.previous_page_number }}"
          >previous</a
        >
        {% endif %}

        <span class="current active">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.next_page_number }}"
          >next</a
        >
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.paginator.num_pages }}"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
    </div>
  </div>
</div>

{% endblock %}

templates/blogposts/create.html
{% extends 'base.html' %}
{% block title %}
Create Post

{% endblock %}
{% block content %}
<div class="row">
  <div class="container">
    <div
      class="col-md mt-5 mx-auto justify-content-center align-items-center"
    >
      <div class="m-5 shadow p-5 text-dark">
        <h1>Create a Post</h1>
        <p>Please, use the following form to log-in:</p>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
  
          <input class="btn btn-secondary px-5" type="submit" value="Create" />
        </form>
        </p>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blogposts/detail.html
{% extends 'base.html' %}
{% block title %}
BlogPosts|{{ objects.title }}

{% endblock %}

{% block content %}
<div class="row my-2">
  <div class=" col-3 ml-5 mt-3">
    <div class="card sticky-top bg-light shadow-lg">
      <img
        width="100px"
        height="250px"
        class="card-img-top rounded-circle p-4"
        src="/media/{{objects.author.profile.photo}}"
        alt="{{objects.author.email}}"
      />
      <div class="card-body">
       
        <h5>Written By:</h5>
        <div class="border-bottom border-warning"></div>
        <p class="lead">{{objects.author.first_name|capfirst}} {{objects.author.last_name|capfirst}}</p>
        <h5>Bio:</h5>
        <div class="border-bottom border-warning"></div>
        <p class="lead text-justify">{{objects.author.profile.bio}}</p>
        
        <h5>Profession:</h5>
        <div class="border-bottom border-warning"></div>
        <p class="lead" >{{objects.author.profile.profession}}</p>
         <a class="btn btn-secondary btn-block text-white h5"
          href="{% url 'blogposts:user_post_list' author=objects.author.username author_id=objects.author.id  %}"
          >All Posts
        </a>
      </div>
    </div>
  </div>
  <div class="col-7 mt-3">
    <div class="title text-dark clearfix">
      <p class="text-uppercase h2 text-justify">{{objects.title}}</p>
      <p class="text-warning" ><hr></p>
      <div class="d-inline-block float-left">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-eye-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
          <path
            fill-rule="evenodd"
            d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
          />
        </svg>
        {{objects.count}}

        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-tags-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 7.586 1H3zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"
          />
          <path
            d="M1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"
          />
        </svg>
        {% for tag in objects.tags.names %} {{tag}} {% endfor %}
      </div>
      <div class="d-inline-block float-right">
        Created: {{objects.created|date}} Modified: {{objects.updated|date}}
      </div>
    </div>
    <div class="border border-seondary mt-3 clearfix"></div>
    <img
     class="mt-3"
      height="300px"
      width="100%"
      src="/media/{{objects.image}}"
      alt=""
    />
    {{objects.body|safe}}
    <br />
  </div>
  <div class="col-2"></div>
</div>
{% endblock %}

templates/blogposts/update.html
{% extends 'base.html' %}
{% block title %}
Update

{% endblock %}
{% block content %}
<div class="row">
  <div class="container">
    <div
      class="col-md mt-5 mx-auto justify-content-center align-items-center"
    >
      <div class="m-5 shadow p-5 text-dark">
        <h1>Update a Post</h1>
        <p>Please, use the following form to log-in:</p>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
  
          <input class="btn btn-secondary px-5" type="submit" value="Update" />
        </form>
        </p>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blogposts/user_list.html

{% extends 'base.html' %}
{% block title %}
{{ request.user.email }} Posts

{% endblock %}

{% block content %}
{% include 'partials/jumbotron.html' with status=objects %}
<div class="row my-2">
  <div class="offset-1 col-3 mt-3">

    <div class="card sticky-top bg-light shadow-lg">
      <img
        width="100px"
        height="200px"
        class="card-img-top rounded-circle p-4"
        src="{% if  user.profile.photo %}/media/{{user.profile.photo}}{% else %}/static/img/anonymous.png{% endif %}"
        alt="{{user.email}}"
      />
      <div class="card-body">
        <h5>Author of this posts:</h5>
        <div class="border-bottom border-warning"></div>
        <p  class="lead">{% if user.first_name %} 
          {{user.first_name|capfirst}} {{user.last_name|capfirst}}  
          {% else %} {{user.email}} {% endif %}</p>
        
        <h5>Bio:</h5>
        <div class="border-bottom border-warning"></div>
        <p  class="text-justify">{% if user.profile.bio %}
           {{user.profile.bio}} {% else %} --- {% endif %}</p>
        
           <h5>Profession:</h5>
           <div class="border-bottom border-warning"></div>
        <p  class="lead">{% if user.profile.profession %}{{user.profile.profession}} {% else %} --- {% endif %}</p>
      <h5>Total Posts:</h5>
      <div class="border-bottom border-warning"></div>
     <p  class="lead">{% if counts %}{{counts}} {% else %} --- {% endif %}</p>
      </div>
    </div>
  </div>
  <div class="col-8">
    {% for obj in objects %}
    <div class="card shadow bg-light d-inline-block m-3" style="width: 20rem;">
      <div class="card-header text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-pencil-square"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
          />
          <path
            fill-rule="evenodd"
            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
          />
        </svg>
        {{obj.author}}
        <li class="float-right list-unstyled">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-clock"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm8-7A8 8 0 1 1 0 8a8 8 0 0 1 16 0z"
          />
          <path
            fill-rule="evenodd"
            d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"
          />
        </svg>
        {{obj.created|date}}</li>
      </div>
      <img
        width="300px"
        height="200px"
        src="/media/{{ obj.image }}"
        class="card-img-top"
        alt="..."
      />
      <div style="height: 8rem;" class="card-body">
        <h6 class="card-title text-justify">{{ obj.title|truncatewords:5 }}</h6>
        <p class="card-text text-justify"></p>
        <a
          href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
          class="btn btn-secondary"
          >Read More...</a
        >
        {% if obj.author.id is request.user.id %}
        <a
        href="{% url 'blogposts:update' author=obj.author author_id=obj.author.id slug=obj.slug %}"
        class="btn btn-secondary"
        >Update</a>
        <a
        href="{% url 'blogposts:delete'  author_id=obj.author.id slug=obj.slug %}"
        class="btn btn-secondary"
        >delete</a>
        {% endif %}
      </div>
      <div class="card-footer text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-eye-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
          <path
            fill-rule="evenodd"
            d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
          />
        </svg>
       <h5 class="badge badge-secondary">{{obj.count}}</h5> 
        <li class="float-right list-unstyled">
        <svg
          class="text-right"
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-tags-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 7.586 1H3zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"
          />
          <path
            d="M1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"
          />
        </svg>
        {% for tag in obj.tags.names %}
     {{tag }}
        {% endfor %}
      </div></li>
    </div>
    {% empty %}
    <div class="d-flex pt-5 justify-content-center align-items-center">
      <p class="bg-warning mt-5 p-5 shadow h1 text-danger">User have no post</p>
    </div>
   
    {% endfor %}
    {% if page_obj.count is not '0' %}
    <div class="pagination row mt-3 text-center">
      <div class="col-6 mx-auto" >
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a class="btn btn-sm btn-warning" href="?page=1">&laquo; first</a>
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.previous_page_number }}"
          >previous</a
        >
        {% endif %}

        <span class="current active">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.next_page_number }}"
          >next</a
        >
        <a
          class="btn btn-sm btn-warning"
          href="?page={{ page_obj.paginator.num_pages }}"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}